
profile:
  active: "dev"


authentication:
  # 60分钟超时
  expire: 60
  api_key: ${SECRET_KEY}

storage:
  type: local
  addr: /data/files

llm:
  type: moonshot
  model_name: "moonshot-v1-8k"
  key: ${OPENAI_KEY}
  endpoint: ${ENDPOINT}


metastore:
  type: "mysql"
  connection_str: ${DB_CONNECTION_STRING}

